name: deploy

on:
  push:
    branches:
      - main

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:           
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v2
         with:
          terraform_version: 1.5.0
          terraform_wrapper: false

       - name: Set up AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        

       - name: Terraform Init
         run: terraform init
         working-directory: ${{ github.workspace }}/test2
     

       - name: Terraform Apply
         run: terraform apply -auto-approve
         working-directory: ${{ github.workspace }}/test2

       - name: t-output
         run: terraform output
         working-directory: ${{ github.workspace }}/test2
         
       - name: Export Terraform output
         id: tf
         run: |
            cd ${{ github.workspace }}/test2
            bucket_name=$(terraform output -raw region2)
            echo "bucket_name=$bucket_name" >> $GITHUB_OUTPUT
      
  
