name: deploy

on:
  push:
    branches:
      - main

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:           
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v2
         with:
          terraform_version: 1.5.0
          terraform_wrapper: false

       - name: List files in root directory
         run: ls -la

       - name: List files in aws-version directory
         run: ls -la test2

       - name: Terraform Init
         run: terraform init
         working-directory: ${{ github.workspace }}/test2
     

       - name: Terraform Apply
         run: terraform apply

       - name: t-output
         run: terraform output
         
       - name: Export Terraform output
         id: tf
         run: |
            bucket_name=$(terraform output -raw region)
            echo "bucket_name=$bucket_name" >> $GITHUB_OUTPUT
      
  
