name: Job output

on:
  push:
    branches: [main]
jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    outputs:
        bucket_name: ${{ steps.tf.outputs.bucket_name}}
        backend_endpoint: ${{ steps.tf.outputs.backend_endpoint }}
        

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name : Terraform apply
        run: terraform apply -auto-approve
  
      - name: Terraform output
        run: terraform output
        
      - name: Export Terraform output
        id: tf
        run: |
          echo "bucket_name=$(terraform output -raw dummy_output)" >> $GITHUB_OUTPUT
          echo "backend_endpoint=testbucket2" >> $GITHUB_OUTPUT
          
  job-2:
      runs-on: ubuntu-latest
      needs: deploy-infrastructure
      steps:
        - name: outputss
          run: echo "the name is ${{ needs.deploy-infrastructure.outputs.bucket_name }}"
