name: Job output

on:
  push:
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      job1_name: ${{steps.set-output.outputs.name }}

    steps:
      - name: set output
        id:   set-output
        run: echo "name=test_name" >> $GITHUB_OUTPUT

      - name: access output
        run: echo "value of the name is ${{steps.set-output.outputs.name }}"
  job2:
     runs-on: ubuntu-latest
     needs: job1
     steps:
       - name: access output
         run: echo "value of name is ${{needs.job1.outputs.job1_name }}"
