name: Job output

on:
  push:
    branches: [main]
jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    outputs:
        bucket_name: ${{ steps.tf.outputs.bucket_name}}
        backend_endpoint: ${{ steps.tf.outputs.backend_endpoint }}
        S3_APP_BUCKET_NAME: ${{steps.tf.outputs.S3_APP_BUCKET_NAME}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    
     

      - name: Export Terraform output
        id: tf
        run: |
          echo "bucket_name=testbucket" >> $GITHUB_OUTPUT
          echo "backend_endpoint=testbucket2" >> $GITHUB_OUTPUT
          echo "S3_APP_BUCKET_NAME=$(terraform output -raw s3_app_bucket_name)" >> $GITHUB_OUTPUT
  job-2:
      runs-on: ubuntu-latest
      needs: deploy-infrastructure
      steps:
        - name: outputss
          run: echo "the name is ${{ needs.deploy-infrastructure.outputs.bucket_name }}"
